additionalRepositories: 
  - url: https://github.com/oulib-datacatalog/celery-remote-worker/tree/test
    checkoutLocation: islandora-remote
 
tasks:
  - name: Setup cyberCommons
    before: cp dc_config/secrets_template.env dc_config/secrets.env
    init: |
      make init
      make build
    command: make run
    
  - name: Setup Islandora remote worker
    before: cd ../islandora-remote
    init: make init
    command: make run

# Ports to expose on workspace startup
ports:
  - port: 80
    onOpen: open-preview
    visibility: private
  - port: 443
    onOpen: ignore
  - port: 5671
    onOpen: ignore
  - port: 27017
    onOpen: ignore

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
