FROM python:3.6-alpine3.9

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PYTHONUNBUFFERED=1 

# Celery Broker and Backend Variables
ENV BROKER_USE_SSL=true
ENV BROKER_URL="amqp://<username>:<password>@<rabbitmq_host>:5671/vhost"
ENV CELERY_RESULT_BACKEND="mongodb://<username>:<password>@<mongo_host>:27017/?ssl=true&ssl_ca_certs=/ssl/testca/cacert.pem&ssl_certfile=/ssl/client/mongodb.pem" 
ENV MONGO_DB="cybercom"
ENV MONGO_TOMBSTONE_COLLECTION="tombstone"
ENV CELERY_IMPORTS=cybercomq
ENV CELERY_SOURCE=git+https://github.com/cybercommons/cybercomq
ENV CELERY_QUEUE=celery
ENV LOG_LEVEL=INFO
RUN apk add git


WORKDIR /  
COPY requirements.txt ./  
RUN pip install --no-cache-dir -r requirements.txt  
RUN rm requirements.txt  


COPY . /app  
WORKDIR /app

#Setup Celery User
RUN addgroup celery && adduser -DH -G celery celery
RUN chown celery:celery -R /app


CMD ["/app/startCeleryWorker"]
