#!/usr/bin/env python3

import os
from subprocess import call

for itm in os.environ.get("CELERY_SOURCE").split(','):
    call(['pip3','install',itm])

celery_queue=os.environ.get("CELERY_QUEUE","celery")
log_level=os.environ.get("LOG_LEVEL","INFO")

call(["celery", "-Q", celery_queue, "-l", log_level, "worker"])
