#!/bin/bash

. cybercom_config.env

docker volume create --name cc_mongo

docker run -it --rm \
  -v cc_mongo:/data/db:z \
  -v "${PWD}"/cybercom_config.env:/config.sh \
  -v "${PWD}"/addmongouser:/addmongouser \
  --entrypoint /addmongouser mongo
